export default [
  {
    id: '1',
    name: 'Нямушка',
    subname: 'с фуа-гра',
    quantity: '2',
    description: 'Печень утки разварная с артишоками.',
    total: '0,5',
    properties: '10 порций, мышь в подарок',
    image: '/uploads/cat.png',
    image2x: '/uploads/cat@2x.png',
  },
  {
    id: '2',
    name: 'Нямушка',
    subname: 'с рыбой',
    quantity: 78,
    description: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
    total: '2',
    properties: '40 порций, 2 мыши в подарок',
    image: '/uploads/cat.png',
    image2x: '/uploads/cat@2x.png',
  },
  {
    id: '3',
    name: 'Нямушка',
    subname: 'с курой',
    quantity: '',
    description: 'Филе из цыплят с трюфелями в бульоне.',
    total: '5',
    properties: '100 порций, 5 мышей в подарок, заказчик доволен',
    image: '/uploads/cat.png',
    image2x: '/uploads/cat@2x.png',
  },
]
